config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/jquery-1" => "pages#jquery_1"
  get "/jquery-2" => "pages#jquery_2"
  get "/jquery-3" => "pages#jquery_3"
  get "/jquery-4" => "pages#jquery_4"
  get "/jquery-5" => "pages#jquery_5"

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :content
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def dispaly_name
    self.email.split("@").first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('id DESC').all # 新贴文方在前面
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxPostingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "jQuery 练习一", jquery_1_path %> |
    <%= link_to "jQuery 练习二", jquery_2_path %> |
    <%= link_to "jQuery 练习三", jquery_3_path %> |
    <%= link_to "jQuery 练习四", jquery_4_path %> |
    <%= link_to "jQuery 练习五", jquery_5_path %>
    <%= yield %>
  </body>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>

  <% if flash[:alert] %>
    <%= flash[:alert] %>
  <% end %>

  <% if current_user %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <%= link_to('change password', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('Signup', new_registration_path(:user)) %> |
    <%= link_to('Login', new_session_path(:user)) %>
  <% end %>
</html>

app/views/pages/jquery_1.html.erb
<script>
 // 这是Javascript 的注解
 // 也可写出 ($function(){
  $ (document).ready(function(){ 
  $("#my-click").click(function(){$("#foo").html('<h1>zoo</h1>');
  })
</script>

<p>
  <a id="my-click">click me</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

app/views/pages/jquery_2.html.erb
<p>
  <a id="my-open-click">Open</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <a id="my-hide-click">Hide</a>
  <p>bar</p>
</div>


<script>
  $("#foo").hide();

  $("#my-open-click").click(function(){
    $("#foo").show();
  })

  $("#my-hide-click").click(function(){
    $("#foo").hide();
  })
</script>

app/views/pages/jquery_3.html.erb
<p>
  <a id="my-toggle-click">Toggle</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<script>
  $("#foo").hide();  //先马上藏起来

  $("#my-toggle-click").hover(function(){
    $("#foo").fadeToggle();  // 移过去会有开关的效果
  })

</script>

app/views/pages/jquery_4.html.erb
<p>
  <a id="my-replace-click">Replace</a>
  <a id="my-remove-click">Remove</a>
  <a id="my-remove-all-click">Remove All</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<div class="zoo">
  <p>a</p>
</div>

<div class="zoo">
  <p>b</p>
</div>

<div class="zoo">
  <p>c</p>
</div>

<script>
  $("#my-replace-click").click(function(){
    $("#foo").replaceWith('<div id="foo" style="border:1px solid green"><p>foo</p></div>');
  })

  $("#my-remove-click").click(function(){
    $("#foo").remove();
  })

  $("#my-remove-all-click").click(function(){
    $(".zoo").remove();
  })
</script>

app/views/pages/jquery_5.html.erb
<style>
  .error {
    color: red;
  }
  .success {
    color: green;
  }
</style>

<p>
  <a id="my-add-class-click">Add Class</a>

  <a id="my-remove-class-click">Remove Class</a>
</p>

<div id="foo">
  <h1>bar</h1>
</div>

<script>
  $("#my-add-class-click").click(function(){
    $("#foo").removeClass('error');
    $("#foo").addClass('success');
  })

  $("#my-remove-class-click").click(function(){
    $("#foo").removeClass('success');
    $("#foo").addClass('error');
  })
</script>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

<div class="panel panel default">
  <div class="panel panel-heading"><%= post.user.display_name %></div>
  <div class="panel-body">
    <%= post.content %>
  </div>
</div>

<% end %>

<div class="dropdown">
    <a class="inputBarA dropdown-toggle" data-toggle="dropdown" href="#">FILTER</a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li role="presentation">
            <a role="menuitem" href="#">Text</a>
        </li>
        <li role="presentation">
            <label>Label name</label>
            <label>Label name</label>
            <label class="checkbox">
                <input type="checkbox">
                Text </label>
            <label class="checkbox">
                <input type="checkbox">
                Text </label>
            <label class="checkbox">
                <input type="checkbox">
                Text </label>
            <label class="checkbox">
                <input type="checkbox">
                Text </label>
        </li>
        <li class="dropdown-submenu">
            <a tabindex="-1" href="#">Centralities</a>
            <ul class="dropdown-menu">
                <label class="radio">
                    <input type="radio" name="options" id="optionsRadios1" value="A" checked>
                    AA </label>
                <label class="radio">
                    <input type="radio" name="options" id="optionsRadios2" value="B">
                    BB </label><label class="radio">
                    <input type="radio" name="options" id="optionsRadios2" value="C">
                    CC </label><label class="radio">
                    <input type="radio" name="options" id="optionsRadios2" value="D">
                    DD </label><label class="radio">
                    <input type="radio" name="options" id="optionsRadios2" value="E">
                    EE </label>
            </ul>
        </li>
    </ul>
</div>


<script>
$('.dropdown-submenu').hover(
        function(){
        //hover in
            $('.dropdown-submenu > ul').css('top', '-' + $('.dropdown-submenu > ul').css('height'));

        },
        //hover out
        function(){
        }
    );

</script>